server:
  port: 8085
  address: localhost
spring:          #表示该配置直接为Spring容器负责处理
　datasource:
    druid:
      a:
        driver-class-name: com.mysql.jdbc.Driver       #配置MySQL的驱动程序类
    　　url: jdbc:mysql://locahost:3306/11?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&zeroDateTimeBehavior=convertToNull
    　　username: admin
    　　password: 123456
    　　dbcp2:
        　　min-idle: 5         #数据库连接池的最小维持连接数
        　　initial-size: 5     #初始化提供的连接数
        　　max-total: 5          #最大的连接数
        　　max-wait-millis: 200        #等待连接获取的最大超时时间
      b:
        driver-class-name: com.mysql.jdbc.Driver       #配置MySQL的驱动程序类
        url: jdbc:mysql://locahost:3306/11?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&zeroDateTimeBehavior=convertToNull
        username: admin
        password: 123456

    mail:
        host: 11
        username: 11
        password: 11
#        port:

